import { ICatalogoRepository, CatalogoCurso, AreaCurso, ModalidadeCurso, NivelCurso } from './CatalogoRepository';

const SEED: CatalogoCurso[] = [
    { id: 'course-1', titulo: 'Oncologia para Técnicos de Enfermagem', slugUrl: 'oncologia-tecnicos', descricaoCurta: 'Especialização em cuidados oncológicos, protocolos de quimioterapia e oncossegurança.', descricaoCompleta: 'Curso completo de especialização voltado para técnicos de enfermagem que atuam ou desejam atuar em serviços de oncologia. Aborda desde a biologia do câncer até a prática segura no preparo e administração de agentes antineoplásicos.', area: 'Oncologia', nivel: 'Especializacao', modalidade: 'Hibrido', cargaHoraria: 240, duracao: '4 meses', preco: 1980, precoOriginal: 2400, parcelamento: 12, imageUrl: 'https://images.unsplash.com/photo-1559757175-0eb30cd8c063?q=80&w=600', destaque: true, ativo: true, inscricoesAbertas: true, proximaTurma: '2026-03-02', totalAlunos: 1240, avaliacao: 4.8, totalAvaliacoes: 312, tags: ['COREN', 'oncossegurança', 'quimioterapia', 'técnico'], instrutores: ['Prof. Marcos Oliveira'], ementa: ['Biologia do Câncer', 'Estadiamento TNM', 'Protocolos de Quimioterapia', 'Oncossegurança', 'Cuidados Paliativos'], certificado: true, reconhecido: true },
    { id: 'course-2', titulo: 'Feridas, Estomias e Incontinências', slugUrl: 'feridas-estomias-incontinencias', descricaoCurta: 'Especialização em estomaterapia para enfermeiros e técnicos. Reconhecida pelo SOBEST.', descricaoCompleta: 'Formação completa em estomaterapia cobrindo classificação de feridas, curativos avançados, manejo de ostomias e incontinência urinária/fecal. Módulos práticos em laboratório de simulação.', area: 'Estomaterapia', nivel: 'Especializacao', modalidade: 'Presencial', cargaHoraria: 320, duracao: '5 meses', preco: 2490, precoOriginal: 3200, parcelamento: 12, imageUrl: 'https://images.unsplash.com/photo-1584820927498-cfe5211fd8bf?q=80&w=600', destaque: true, ativo: true, inscricoesAbertas: true, proximaTurma: '2026-03-10', totalAlunos: 890, avaliacao: 4.9, totalAvaliacoes: 245, tags: ['SOBEST', 'feridas', 'estomia', 'curativo'], instrutores: ['Prof.a Dra. Carla Bezerra'], ementa: ['Anatomia Cutânea', 'Classificação de Feridas', 'Curativos Avançados', 'Ostomias de Eliminação', 'Incontinência Urinária'], certificado: true, reconhecido: true },
    { id: 'course-3', titulo: 'UTI Adulto e Cuidados Intensivos', slugUrl: 'uti-adulto-cuidados-intensivos', descricaoCurta: 'Especialização completa para enfermeiros de UTI. Ventilação, monitorização e emergências.', descricaoCompleta: 'Programa intensivo para capacitação em medicina e enfermagem intensiva. Cobre pacientes críticos, ventilação mecânica, monitorização hemodinâmica e protocolos de emergência.', area: 'UTI e Cuidados Intensivos', nivel: 'Especializacao', modalidade: 'Hibrido', cargaHoraria: 360, duracao: '6 meses', preco: 2890, precoOriginal: null, parcelamento: 12, imageUrl: 'https://images.unsplash.com/photo-1516549655169-df83a0774514?q=80&w=600', destaque: true, ativo: true, inscricoesAbertas: true, proximaTurma: '2026-04-01', totalAlunos: 2100, avaliacao: 4.7, totalAvaliacoes: 580, tags: ['UTI', 'ventilação', 'emergência', 'monitorização'], instrutores: ['Dr. Ricardo Campos', 'Enf.a Patrícia Nunes'], ementa: ['Monitorização Hemodinâmica', 'Ventilação Mecânica', 'Sepse e Choque', 'Parada Cardiorrespiratória', 'Cuidados Neurológicos'], certificado: true, reconhecido: true },
    { id: 'course-4', titulo: 'Enfermagem Oncológica', slugUrl: 'enfermagem-oncologica', descricaoCurta: 'Especialização pós-graduação lato sensu para enfermeiros. 360h com estágio supervisionado.', descricaoCompleta: 'Pós-graduação lato sensu com foco na prática avançada de enfermagem em oncologia. Inclui estágio supervisionado em hospitais parceiros e defesa de TCC.', area: 'Oncologia', nivel: 'Especializacao', modalidade: 'Presencial', cargaHoraria: 360, duracao: '8 meses', preco: 3490, precoOriginal: 4200, parcelamento: 18, imageUrl: 'https://images.unsplash.com/photo-1576091160399-112ba8d25d1d?q=80&w=600', destaque: false, ativo: true, inscricoesAbertas: true, proximaTurma: '2026-04-15', totalAlunos: 650, avaliacao: 4.9, totalAvaliacoes: 178, tags: ['pós-graduação', 'TCC', 'estágio', 'oncologia'], instrutores: ['Prof.a Dra. Carla Bezerra', 'Dr. Ricardo Campos'], ementa: ['Oncologia Clínica', 'Farmacologia Antineoplásica', 'Enfermagem em Radioterapia', 'Cuidados Paliativos Avançados', 'TCC'], certificado: true, reconhecido: true },
    { id: 'course-5', titulo: 'Centro Cirúrgico e CME', slugUrl: 'centro-cirurgico-cme', descricaoCurta: 'Especialização em enfermagem perioperatória e central de material e esterilização.', descricaoCompleta: 'Programa voltado para profissionais que atuam ou desejam atuar em centro cirúrgico, sala de recuperação pós-anestésica e central de material esterilizado.', area: 'Centro Cirurgico', nivel: 'Especializacao', modalidade: 'Presencial', cargaHoraria: 280, duracao: '5 meses', preco: 2190, precoOriginal: 2800, parcelamento: 12, imageUrl: 'https://images.unsplash.com/photo-1551601651-bc60f254d532?q=80&w=600', destaque: false, ativo: true, inscricoesAbertas: false, proximaTurma: '2026-07-01', totalAlunos: 430, avaliacao: 4.6, totalAvaliacoes: 112, tags: ['cirúrgico', 'CME', 'perioperatório', 'anestesia'], instrutores: ['Enf. Thiago Mendes'], ementa: ['Anatomia Cirúrgica', 'Assistência Perioperatória', 'Esterilização e Desinfecção', 'Instrumentação Cirúrgica', 'SRPA'], certificado: true, reconhecido: true },
    { id: 'course-6', titulo: 'Gestão em Saúde e Liderança', slugUrl: 'gestao-saude-lideranca', descricaoCurta: 'MBA executivo para gestores de saúde. Administração hospitalar, finanças e liderança.', descricaoCompleta: 'MBA voltado para coordenadores, gerentes e diretores de unidades de saúde. Aborda administração hospitalar, gestão de pessoas, indicadores de saúde e planejamento estratégico.', area: 'Gestao em Saude', nivel: 'MBA', modalidade: 'Hibrido', cargaHoraria: 420, duracao: '8 meses', preco: 4890, precoOriginal: 5800, parcelamento: 24, imageUrl: 'https://images.unsplash.com/photo-1454165804606-c3d57bc86b40?q=80&w=600', destaque: true, ativo: true, inscricoesAbertas: true, proximaTurma: '2026-02-01', totalAlunos: 1850, avaliacao: 4.8, totalAvaliacoes: 423, tags: ['MBA', 'gestão hospitalar', 'liderança', 'finanças'], instrutores: ['Prof.a Dra. Carla Bezerra', 'Dr. Ricardo Campos'], ementa: ['Administração Hospitalar', 'Indicadores de Saúde', 'Gestão de Pessoas', 'Finanças para Gestores', 'Planejamento Estratégico'], certificado: true, reconhecido: false },
    { id: 'course-7', titulo: 'Saúde Mental e Enfermagem Psiquiátrica', slugUrl: 'saude-mental-enfermagem-psiquiatrica', descricaoCurta: 'Especialização em cuidado de saúde mental, CAPS, RAPS e reabilitação psicossocial.', descricaoCompleta: 'Formação especializada para profissionais que atuam na Rede de Atenção Psicossocial (RAPS), CAPS, clínicas psiquiátricas e enfermarias. Aborda psicopatologia, psicofarmacologia e reabilitação.', area: 'Saude Mental', nivel: 'Especializacao', modalidade: 'EAD', cargaHoraria: 240, duracao: '4 meses', preco: 1490, precoOriginal: 1980, parcelamento: 12, imageUrl: 'https://images.unsplash.com/photo-1494178270175-e96de2971df9?q=80&w=600', destaque: false, ativo: true, inscricoesAbertas: true, proximaTurma: '2026-04-01', totalAlunos: 720, avaliacao: 4.7, totalAvaliacoes: 198, tags: ['saúde mental', 'CAPS', 'psiquiatria', 'EAD'], instrutores: ['Psic. Fernanda Souza'], ementa: ['Psicopatologia', 'Psicofarmacologia', 'RAPS e CAPS', 'Reabilitação Psicossocial', 'Crise e Suicídio'], certificado: true, reconhecido: false },
];

export class MockCatalogoRepository implements ICatalogoRepository {
    private cursos: CatalogoCurso[] = JSON.parse(JSON.stringify(SEED));

    async findAll(filtros?: { area?: AreaCurso; modalidade?: ModalidadeCurso; nivel?: NivelCurso; inscricoesAbertas?: boolean }): Promise<CatalogoCurso[]> {
        let result = this.cursos.filter(c => c.ativo);
        if (filtros?.area) result = result.filter(c => c.area === filtros.area);
        if (filtros?.modalidade) result = result.filter(c => c.modalidade === filtros.modalidade);
        if (filtros?.nivel) result = result.filter(c => c.nivel === filtros.nivel);
        if (filtros?.inscricoesAbertas !== undefined) result = result.filter(c => c.inscricoesAbertas === filtros.inscricoesAbertas);
        return result;
    }

    async findById(id: string): Promise<CatalogoCurso | null> {
        return this.cursos.find(c => c.id === id) ?? null;
    }

    async findBySlug(slug: string): Promise<CatalogoCurso | null> {
        return this.cursos.find(c => c.slugUrl === slug) ?? null;
    }

    async findDestaques(): Promise<CatalogoCurso[]> {
        return this.cursos.filter(c => c.destaque && c.ativo);
    }

    async findRelacionados(cursoId: string): Promise<CatalogoCurso[]> {
        const curso = this.cursos.find(c => c.id === cursoId);
        if (!curso) return [];
        return this.cursos.filter(c => c.id !== cursoId && c.area === curso.area && c.ativo).slice(0, 3);
    }
}
